# 1. 用Eigengrau當作背景顏色
# 2. 二分逼近法調整Eigengrau亮度當作前景顏色
# 3. 設定Cursor
# 4. 二分逼近法調整Eigengrau亮度當作兩種灰色
# 5. 挑選每個顏色Hue值
# 6. 用二分逼近法調整每個顏色HSL亮度

# 挑選的Hue值
# 0	red
# 15
# 30	orange brown
# 45	yellow
# 60
# 75	lime
# 90	green
# 105
# 120
# 135	cyan
# 150
# 165
# 180	teal
# 195
# 210
# 225	blue
# 240   foreground, background and visual
# 255
# 270	purple
# 285
# 300
# 315	magenta
# 330
# 345
# 360	red

[font.normal]
family = "Fira Code"
style = "Retina"

[colors.primary]
foreground = "#efeff3"
background = "#16161d"

[colors.cursor]
text = "#16161d"
cursor = "#efeff3"

[colors.normal]
black = "#16161d"
red = "#ff8080"
green = "#d7ff5e"
yellow = "#ffd75e"
blue = "#809fff"
magenta = "#cf9fff"
cyan = "#00dfdf"
white = "#47475e"

[colors.bright]
black = "#22222d"
red = "#bf6000"
green = "#60bf00"
yellow = "#ff9f40"
blue = "#7c7c9c"
magenta = "#ff80df"
cyan = "#80ff9f"
white = "#efeff3"
