[colors.primary]
foreground = "#fafafa"
background = "#0a0a0a"

[colors.cursor]
text = "#0a0a0a"
cursor = "#fafafa"

[colors.normal]
black = "#0a0a0a"
red = "#fb7185"
green = "#bef264"
yellow = "#fcd34d"
blue = "#60a5fa"
magenta = "#a78bfa"
cyan = "#22d3ee"
white = "#404040"

[colors.bright]
black = "#171717"
red = "#f472b6"
green = "#4ade80"
yellow = "#fb923c"
blue = "#818cf8"
magenta = "#e879f9"
cyan = "#2dd4bf"
white = "#fafafa"
