[colors.primary]
background = "#0a0a0a"
foreground = "#fafafa"

[colors.cursor]
text = "#0a0a0a"
cursor = "#fafafa"

[colors.normal]
black = "#0a0a0a"
white = "#171717"
blue = "#60a5fa"
cyan = "#67e8f9"
green = "#bef264"
magenta = "#c084fc"
red = "#fb7185"
yellow = "#fcd34d"

[colors.bright]
black = "#404040"
white = "#fafafa"
blue = "#38bdf8"
cyan = "#2dd4bf"
green = "#4ade80"
magenta = "#e879f9"
red = "#f472b6"
yellow = "#fb923c"
