vim.g.colors_name = 'hsuyuting'


vim.api.nvim_set_hl(0, 'CursorLine', { bg = '#22222d' })
vim.api.nvim_set_hl(0, 'Directory', { fg = '#809fff' })
vim.api.nvim_set_hl(0, 'DiffAdd', { fg = '#d7ff5e' })
vim.api.nvim_set_hl(0, 'DiffChange', { fg = '#ffd75e' })
vim.api.nvim_set_hl(0, 'DiffDelete', { fg = '#ff8080' })
vim.api.nvim_set_hl(0, 'ErrorMsg', { fg = '#ff8080', underline = true })
vim.api.nvim_set_hl(0, 'WinSeparator', { fg = '#22222d' })
vim.api.nvim_set_hl(0, 'SignColumn', {})
vim.api.nvim_set_hl(0, 'IncSearch', { link = 'Search' })
vim.api.nvim_set_hl(0, 'LineNr', { fg = '#47475e' })
vim.api.nvim_set_hl(0, 'CursorLineNr', { bg = '#22222d', fg = '#efeff3' })
vim.api.nvim_set_hl(0, 'CursorLineSign', {})
vim.api.nvim_set_hl(0, 'MatchParen', { bg = '#00dfdf', fg = '#16161d' })
vim.api.nvim_set_hl(0, 'ModeMsg', { fg = '#47475e' })
vim.api.nvim_set_hl(0, 'MoreMsg', { fg = '#47475e' })
vim.api.nvim_set_hl(0, 'NonText', { fg = '#22222d' })
vim.api.nvim_set_hl(0, 'Normal', { bg = '#16161d', fg = '#efeff3' })
vim.api.nvim_set_hl(0, 'NormalFloat', { link = 'Normal' })
vim.api.nvim_set_hl(0, 'Pmenu', { bg = '#16161d', fg = '#47475e' })
vim.api.nvim_set_hl(0, 'PmenuSel', { bg = '#22222d', fg = '#efeff3' })
vim.api.nvim_set_hl(0, 'PmenuSbar', { bg = '#16161d' })
vim.api.nvim_set_hl(0, 'PmenuThumb', { bg = '#22222d' })
vim.api.nvim_set_hl(0, 'Question', { fg = '#efeff3' })
vim.api.nvim_set_hl(0, 'Search', { bg = '#00dfdf', fg = '#16161d' })
vim.api.nvim_set_hl(0, 'SpecialKey', { fg = '#cf9fff' })
vim.api.nvim_set_hl(0, 'StatusLine', { fg = '#efeff3' })
vim.api.nvim_set_hl(0, 'StatusLineNC', { fg = '#47475e' })
vim.api.nvim_set_hl(0, 'TabLine', { fg = '#47475e' })
vim.api.nvim_set_hl(0, 'TabLineFill', {})
vim.api.nvim_set_hl(0, 'TabLineSel', { fg = '#efeff3' })
vim.api.nvim_set_hl(0, 'Title', { fg = '#809fff' })
vim.api.nvim_set_hl(0, 'Visual', { bg = '#7c7c9c' })
vim.api.nvim_set_hl(0, 'WarningMsg', { fg = '#ffd75e' })
vim.api.nvim_set_hl(0, 'Comment', { fg = '#47475e' })
vim.api.nvim_set_hl(0, 'Constant', { fg = '#ffd75e' })
vim.api.nvim_set_hl(0, 'String', { fg = '#ffd75e' })
vim.api.nvim_set_hl(0, 'Identifier', { fg = '#d7ff5e' })
vim.api.nvim_set_hl(0, 'Function', { fg = '#ff9f40' })
vim.api.nvim_set_hl(0, 'Statement', { fg = '#809fff' })
vim.api.nvim_set_hl(0, 'PreProc', { fg = '#809fff' })
vim.api.nvim_set_hl(0, 'Type', { fg = '#ff8080' })
vim.api.nvim_set_hl(0, 'Special', { fg = '#cf9fff' })
vim.api.nvim_set_hl(0, 'Underlined', { fg = '#00dfdf', underline = true })
vim.api.nvim_set_hl(0, 'CopilotSuggestion', { fg = '#47475e' })
vim.api.nvim_set_hl(0, '@string.special.url', { link = 'Underlined' })
vim.api.nvim_set_hl(0, '@comment.error', { fg = '#ff8080' })
vim.api.nvim_set_hl(0, '@comment.warning', { fg = '#ffd75e' })
vim.api.nvim_set_hl(0, '@comment.todo', { fg = '#ffd75e' })
vim.api.nvim_set_hl(0, 'Added', { fg = '#d7ff5e' })
vim.api.nvim_set_hl(0, 'Removed', { fg = '#ff8080' })
vim.api.nvim_set_hl(0, 'Changed', { fg = '#ffd75e' })
vim.api.nvim_set_hl(0, 'DiagnosticError', { fg = '#ff8080' })
vim.api.nvim_set_hl(0, 'DiagnosticWarn', { fg = '#ffd75e' })
vim.api.nvim_set_hl(0, '@tag.attribute', { link = 'Identifier' })
vim.api.nvim_set_hl(0, '@tag.html', { link = 'Statement' })
